# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# 相关文件:
# - Program/Program.csproj
# - README.md

name: .NET 发布

env:
  PROJECT_FILE: 'Program/Program.csproj'
  TARGET_FRAMEWORK: 'net9.0'
  DOTNET_VERSION: '9.0.x'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '发布 Tag (如 v1.0.0)'
        required: true
        default: 'v3.7.0'
      name:
        description: '发布名称'
        required: true
        default: 'v3.7.0'
      body:
        description: '发布内容'
        required: false
        default: ''
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: 配置 .NET 环境
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 还原依赖
      run: dotnet restore


    - name: 发布 win-x64 (独立运行)
      run: dotnet publish ${{ env.PROJECT_FILE }} -o Release/win-x64-self-contained -r win-x64 --self-contained true --framework ${{ env.TARGET_FRAMEWORK }} -p:PublishSingleFile=true

    - name: 发布 linux-x64 (独立运行)
      run: dotnet publish ${{ env.PROJECT_FILE }} -o Release/linux-x64-self-contained -r linux-x64 --self-contained true --framework ${{ env.TARGET_FRAMEWORK }} -p:PublishSingleFile=true

    - name: 发布 linux-arm64 (独立运行)
      run: dotnet publish ${{ env.PROJECT_FILE }} -o Release/linux-arm64-self-contained -r linux-arm64 --self-contained true --framework ${{ env.TARGET_FRAMEWORK }} -p:PublishSingleFile=true

    - name: 移除 PDB 文件
      run: |

           rm -rf Release/win-x64-self-contained/*.pdb
           rm -rf Release/linux-x64-self-contained/*.pdb
           rm -rf Release/linux-arm64-self-contained/*.pdb

    - name: 压缩文件
      run: |
           mkdir z
           cd Release

           zip -r ../z/win-x64-self-contained.zip win-x64-self-contained/
           zip -r ../z/linux-x64-self-contained.zip linux-x64-self-contained/
           zip -r ../z/linux-arm64-self-contained linux-arm64-self-contained/
           cd ..

    - name: 写入发布内容
      run: |
           echo -e "${{ inputs.body }}" > z/body.txt

    - name: 发布 Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: z/body.txt
        name: ${{ inputs.name }}
        tag_name: ${{ inputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
        # upload except pdb file
        files: |

          z/win-x64-self-contained.zip
          z/linux-x64-self-contained.zip
          z/linux-arm64-self-contained.zip
